# Generated by Django 5.1.1 on 2024-11-07 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CertificacionCurso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("nombre_academia", models.CharField(max_length=255)),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ExperienciaLaboral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("puesto_trabajo", models.CharField(max_length=255)),
                ("fecha_inicio", models.DateField()),
                ("fecha_final", models.DateField(blank=True, null=True)),
                ("nombre_empresa", models.CharField(max_length=255)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("logros_obtenidos", models.TextField(blank=True, null=True)),
                ("referencias", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="FormacionAcademica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("nombre_academia", models.CharField(max_length=255)),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField(blank=True, null=True)),
                ("referencias", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="HardSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Idioma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("nivel", models.CharField(max_length=50)),
                ("certificaciones", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Proyecto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("descripcion", models.TextField()),
                ("enlace", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Publicacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doi", models.CharField(blank=True, max_length=100, null=True)),
                ("url", models.URLField(blank=True, null=True)),
                ("rol", models.CharField(max_length=255)),
                ("nombre", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ReconocimientoPremio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("entidad", models.CharField(max_length=255)),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SoftSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("nombre", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Voluntariado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("puesto_voluntariado", models.CharField(max_length=255)),
                ("fecha_inicio", models.DateField()),
                ("fecha_final", models.DateField(blank=True, null=True)),
                ("nombre_entidad", models.CharField(max_length=255)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("logros_obtenidos", models.TextField(blank=True, null=True)),
                ("referencias", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("direccion", models.CharField(max_length=255)),
                ("telefono", models.CharField(max_length=20)),
                ("correo_electronico_1", models.EmailField(max_length=254)),
                (
                    "correo_electronico_2",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("dni", models.CharField(max_length=20, unique=True)),
                ("url", models.URLField(blank=True, null=True)),
                ("biografia", models.TextField(blank=True, null=True)),
                (
                    "certificaciones_cursos",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile_cv.certificacioncurso",
                    ),
                ),
                (
                    "experiencias_laborales",
                    models.ManyToManyField(
                        blank=True, to="profile_cv.experiencialaboral"
                    ),
                ),
                (
                    "formaciones_academicas",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile_cv.formacionacademica",
                    ),
                ),
                (
                    "hard_skills",
                    models.ManyToManyField(blank=True, to="profile_cv.hardskill"),
                ),
                ("idiomas", models.ManyToManyField(blank=True, to="profile_cv.idioma")),
                (
                    "proyectos",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile_cv.proyecto",
                    ),
                ),
                (
                    "publicaciones",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile_cv.publicacion",
                    ),
                ),
                (
                    "reconocimientos_premios",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile_cv.reconocimientopremio",
                    ),
                ),
                (
                    "soft_skills",
                    models.ManyToManyField(blank=True, to="profile_cv.softskill"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile_cv.user",
                    ),
                ),
                (
                    "voluntariados",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile_cv.voluntariado",
                    ),
                ),
            ],
        ),
    ]
