# Generated by Django 4.2.16 on 2024-11-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_cv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificacioncurso',
            name='current_course',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='current_job',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formacionacademica',
            name='current_education',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='disability',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='disability_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='incorporation',
            field=models.CharField(blank=True, choices=[('INMEDIATAMENTE', 'Inmediatamente'), ('_15_DIAS', '_15_Dias'), ('_7_DIAS', '_7_Dias')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='open_to_work',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sector',
            field=models.CharField(blank=True, choices=[('IT', 'It'), ('SALUT', 'Salut'), ('OTRO', 'Otro')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='vehicle',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='voluntariado',
            name='current_volunteering',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
