# Generated by Django 5.1.1 on 2024-11-15 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile_cv", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hardskill",
            name="name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PYTHON", "Python"),
                    ("JAVA", "Java"),
                    ("JAVASCRIPT", "JavaScript"),
                    ("C_PLUS_PLUS", "C++"),
                    ("SQL", "SQL"),
                    ("HTML", "HTML"),
                    ("CSS", "CSS"),
                    ("RUBY", "Ruby"),
                    ("PHP", "PHP"),
                    ("SWIFT", "Swift"),
                    ("GO", "Go"),
                    ("KOTLIN", "Kotlin"),
                    ("R", "R"),
                    ("SCALA", "Scala"),
                    ("PERL", "Perl"),
                    ("MATLAB", "MATLAB"),
                    ("VHDL", "VHDL"),
                    ("VERILOG", "Verilog"),
                    ("ASSEMBLY", "Assembly"),
                    ("OTHER", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="incorporation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("IMMEDIATELY", "Immediately"),
                    ("_15_DAYS", "15 Days"),
                    ("_7_DAYS", "7 Days"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="softskill",
            name="name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("COMMUNICATION", "Communication"),
                    ("TEAMWORK", "Teamwork"),
                    ("PROBLEM_SOLVING", "Problem Solving"),
                    ("TIME_MANAGEMENT", "Time Management"),
                    ("ADAPTABILITY", "Adaptability"),
                    ("CREATIVITY", "Creativity"),
                    ("LEADERSHIP", "Leadership"),
                    ("WORK_ETHIC", "Work Ethic"),
                    ("INTERPERSONAL_SKILLS", "Interpersonal Skills"),
                    ("CRITICAL_THINKING", "Critical Thinking"),
                    ("OTHER", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="User_cv",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("has_address", models.BooleanField(blank=True, null=True)),
                ("has_phone", models.BooleanField(blank=True, null=True)),
                ("has_email_1", models.BooleanField(blank=True, null=True)),
                ("has_email_2", models.BooleanField(blank=True, null=True)),
                ("has_dni", models.BooleanField(blank=True, null=True)),
                ("has_url", models.BooleanField(blank=True, null=True)),
                ("has_biography", models.BooleanField(blank=True, null=True)),
                ("has_open_to_work", models.BooleanField(blank=True, null=True)),
                ("has_vehicle", models.BooleanField(null=True)),
                ("has_disability", models.BooleanField(blank=True, null=True)),
                (
                    "has_disability_percentage",
                    models.BooleanField(blank=True, null=True),
                ),
                ("has_incorporation", models.BooleanField(blank=True, null=True)),
                ("has_sector", models.BooleanField(blank=True, null=True)),
                ("has_work_experiences", models.BooleanField(blank=True, null=True)),
                ("has_hard_skills", models.BooleanField(blank=True, null=True)),
                ("has_soft_skills", models.BooleanField(blank=True, null=True)),
                ("has_languages", models.BooleanField(blank=True, null=True)),
                ("has_academic_educations", models.BooleanField(blank=True, null=True)),
                ("has_volunteerings", models.BooleanField(blank=True, null=True)),
                ("has_projects", models.BooleanField(blank=True, null=True)),
                ("has_publications", models.BooleanField(blank=True, null=True)),
                ("has_recognitions_awards", models.BooleanField(blank=True, null=True)),
                (
                    "has_certifications_courses",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile_cv.profile",
                    ),
                ),
            ],
        ),
    ]
