# Generated by Django 5.1.1 on 2024-11-20 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile_cv", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile_cv",
            old_name="phone",
            new_name="phone_1",
        ),
        migrations.RenameField(
            model_name="user_cv",
            old_name="has_phone",
            new_name="has_phone_1",
        ),
        migrations.CreateModel(
            name="CategoryUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile_cv.category",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="profile_cv",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="profile_cv.categoryuser",
            ),
        ),
        migrations.CreateModel(
            name="IncorporationUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "incorporation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile_cv.incorporation",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="profile_cv",
            name="incorporation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="profile_cv.incorporationuser",
            ),
        ),
        migrations.CreateModel(
            name="SectorUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile_cv.sector",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="profile_cv",
            name="sector",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="profile_cv.sectoruser"
            ),
        ),
    ]
