# Generated by Django 5.1.1 on 2024-11-20 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profile_cv", "0002_rename_phone_profile_cv_phone_1_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="softskilluser",
            name="level_skill",
        ),
    ]
