# Generated by Django 5.1.1 on 2024-11-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "profile_cv",
            "0002_alter_hardskill_name_alter_profile_incorporation_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SOFTWARE_DEVELOPMENT", "Software Development"),
                    ("DATA_SCIENCE", "Data Science"),
                    ("CYBER_SECURITY", "Cyber Security"),
                    ("NETWORK_ENGINEERING", "Network Engineering"),
                    ("SYSTEM_ADMINISTRATION", "System Administration"),
                    ("CLOUD_COMPUTING", "Cloud Computing"),
                    ("DEVOPS", "DevOps"),
                    ("IT_SUPPORT", "IT Support"),
                    ("DATABASE_ADMINISTRATION", "Database Administration"),
                    ("ARTIFICIAL_INTELLIGENCE", "Artificial Intelligence"),
                    ("MACHINE_LEARNING", "Machine Learning"),
                    ("WEB_DEVELOPMENT", "Web Development"),
                    ("MOBILE_DEVELOPMENT", "Mobile Development"),
                    ("GAME_DEVELOPMENT", "Game Development"),
                    ("IT_CONSULTING", "IT Consulting"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user_cv",
            name="has_category",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="sector",
            field=models.CharField(
                blank=True, choices=[("IT", "It")], max_length=50, null=True
            ),
        ),
    ]
